spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  spring:
    data:
      redis:
        host: localhost
        port: 6379

  springdoc:
    swagger-ui:
      path: /swagger-ui.html